### ISSUE TITLE
Upgrade eightpoints/guzzle-bundle

### ISSUE THREAD

**Issue by stingus** [solvecrew/ExpoNotificationsBundle#10]
Hi,
Thank you for the bundle, just made it a whole lot easier for us to implement Expo push notifications. Do you think it's safe to upgrade the bundle to use eightpoints/guzzle-bundle ^6.0? We have some dependencies to use guzzle-bundle 6.1 and we'd rather not downgrade to 5.3.

Thanks!

**Comment by solvecrew** [comment]
Hey there!
You're welcome! Always nice to share some of our work!  We'll look into this, but it will be at the beginning of the next month. If you can't wait so long, please feel free to submit a pull request ;)

Cheers!

**Comment by stingus** [comment]
Sure, I'll test it with 6.0 and come back with a PR.

**Comment by stingus** [comment]
Created #11
