### ISSUE TITLE
Service "sc_expo_notifications.notification_manager" not found

### ISSUE THREAD

**Issue by Systemcheck** [solvecrew/ExpoNotificationsBundle#23]
As Title says i cant access notification_manager.
i call how in Doc described with: 
`$notificationManager = $this->get('sc_expo_notifications.notification_manager');`

First i filled the config.yaml, later i removed all. Both the same error.
Symfony 4.2
Whats the problem there? the install was without errors.
 ![screen](https://user-images.githubusercontent.com/11903310/63988344-11195700-cadc-11e9-9f70-a62a2a727d36.PNG)

**Comment by FloDev974** [comment]
Hi try this 
 $notificationManager = $this->container->get('sc_expo_notifications.notification_manager');
is work for me on Symfony 4.1

**Comment by FloDev974** [comment]
Hi try this
`$notificationManager = $this->container->get('sc_expo_notifications.notification_manager');`
is work for me on Symfony 4.1

**Comment by Systemcheck** [comment]
same Issue. Service is not available. I removed the bundle now and send Notifications with curl. thx.
